import io
import os
import sys
import traceback
from typing import List, Optional, TypedDict

from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from langchain_core.messages import BaseMessage, HumanMessage
from langchain_core.runnables import RunnableLambda
from langchain_core.tools import tool
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import END, START, StateGraph
from langserve import add_routes
from pydantic import BaseModel, Field


# ==========================================
# 1. INPUT MODEL FOR LANGSERVE PLAYGROUND
# ==========================================
class AgentInput(BaseModel):
    task: str = Field(
        ...,
        description="Describe the Python program you want the agent to create."
    )


# ==========================================
# 2. LLM INITIALIZATION
# ==========================================
api_key = os.getenv("GOOGLE_API_KEY")

if not api_key:
    raise ValueError(
        "GOOGLE_API_KEY is missing. Add it in Render Environment Variables."
    )

llm_flash = ChatGoogleGenerativeAI(
    model=os.getenv("GEMINI_MODEL", "gemini-2.5-flash"),
    google_api_key=api_key,
    temperature=0.2,
)


# ==========================================
# 3. GRAPH STATE
# ==========================================
class CrewState(TypedDict, total=False):
    task: str
    messages: List[BaseMessage]
    code: Optional[str]
    report: Optional[str]


# ==========================================
# 4. GEMINI RESPONSE HELPER
# ==========================================
def get_text_content(response) -> str:
    content = response.content

    if isinstance(content, str):
        return content.strip()

    if isinstance(content, list):
        return "\n".join(
            item.get("text", "") if isinstance(item, dict) else str(item)
            for item in content
        ).strip()

    return str(content).strip()


# ==========================================
# 5. TOOLS
# ==========================================
@tool
def run_python_code(code: str) -> str:
    """
    Run generated Python code.

    Warning: This is unsafe for a public deployment because it runs
    code generated by an LLM. Use only for learning/private projects.
    """
    clean_code = str(code).replace("```python", "").replace("```", "").strip()

    old_stdout = sys.stdout
    new_stdout = io.StringIO()
    sys.stdout = new_stdout

    try:
        execution_scope = {}
        exec(clean_code, execution_scope)
        result = new_stdout.getvalue()

    except Exception:
        result = f"Execution Error:\n{traceback.format_exc()}"

    finally:
        sys.stdout = old_stdout

    return result.strip() or "Success (no terminal output)"


@tool
def generate_test_cases(task_description: str) -> str:
    """Generate standard and edge-case tests for a coding task."""
    prompt = f"""
You are a Senior QA Engineer.

Generate 3 to 5 highly specific test scenarios for this coding task:

{task_description}

Include standard cases and edge cases.
Return a numbered list.
Do not claim that tests were executed.
"""

    response = llm_flash.invoke(prompt)
    return get_text_content(response)


# ==========================================
# 6. LANGGRAPH NODES
# ==========================================
def prepare_task_node(state: CrewState) -> dict:
    """Converts the input textbox value into a LangChain message."""
    return {
        "messages": [HumanMessage(content=state["task"])]
    }


def real_time_developer(state: CrewState) -> dict:
    task = state["messages"][-1].content

    prompt = f"""
You are a senior Python developer.

Write a clean, self-contained Python script for this task:

{task}

Return only Python code.
Do not include explanations or Markdown code fences.
"""

    response = llm_flash.invoke(prompt)

    return {
        "code": get_text_content(response)
    }


def real_time_tester(state: CrewState) -> dict:
    task = state["messages"][-1].content
    code = state.get("code", "")

    test_cases = generate_test_cases.invoke(
        {"task_description": task}
    )

    # Retains the behavior of your original notebook.
    execution_result = run_python_code.invoke(
        {"code": code}
    )

    report = f"""### EXECUTION OUTPUT:
{execution_result}

### TEST SCENARIOS GENERATED:
{test_cases}
"""

    return {
        "report": report
    }


# ==========================================
# 7. BUILD LANGGRAPH
# ==========================================
workflow = StateGraph(CrewState)

workflow.add_node("prepare_task", prepare_task_node)
workflow.add_node("developer", real_time_developer)
workflow.add_node("tester", real_time_tester)

workflow.add_edge(START, "prepare_task")
workflow.add_edge("prepare_task", "developer")
workflow.add_edge("developer", "tester")
workflow.add_edge("tester", END)

rt_app = workflow.compile()


# ==========================================
# 8. FASTAPI APPLICATION
# ==========================================
app = FastAPI(
    title="LangGraph Code Generation Agent",
    version="1.0.0",
    description="A LangGraph and Gemini agent that generates Python code and test cases.",
)


@app.get("/", response_class=HTMLResponse)
def home():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>LangGraph Code Agent</title>
    </head>
    <body style="font-family: Arial, sans-serif; max-width: 720px; margin: 60px auto;">
        <h1>LangGraph Code Agent is live</h1>
        <p>This agent generates Python code, runs it, and creates QA test cases.</p>
        <p><a href="/agent/playground/">Open Agent Playground</a></p>
        <p><a href="/docs">Open FastAPI Documentation</a></p>
    </body>
    </html>
    """


# Return only final useful results in the playground.
agent_api = (
    rt_app
    | RunnableLambda(
        lambda result: {
            "generated_code": result.get("code", ""),
            "test_report": result.get("report", ""),
        }
    )
).with_types(input_type=AgentInput)

add_routes(
    app,
    agent_api,
    path="/agent",
)


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        app,
        host="0.0.0.0",
        port=int(os.getenv("PORT", "8000")),
    )
